### ISSUE TITLE
Yahoo Finance blocking requests

### ISSUE THREAD

**Issue by samjmck** [samjmck/tobcalc#10]
This is causing issues with checking the type of security of an ISIN as well as whether a fund is accumulating or distributing.

**Comment by vivienbo** [comment]
Hi,

I think your idea of using the OpenFIGI API to (listed in the README) for this purpose is probably a good way to go:
* their POST /v3/mapping seems adequate
    * it can allow for up to 5 requests per minute of 10 jobs (= 50 securities per minute)
    * it can allow for up to 25 requests per minute of 100 jobs (= 2500 securities per minute) with API key
* I noticed [this fork's branch](https://github.com/debiewouter/tobcalc/tree/feature/etrade) which aims at implementing eTrade support. Issue is that:
    * eTrade uses a combination of `Market` (with an unidentified code scheme) and `Ticker` or `CUSIP` to identify a security
    * while the `CUSIP` can easily be converted to `ISIN` (modulo whether the format of the CUSIP includes the country or whether it could be probed based on `Market`), the `ticker` really requires to be matched with the `Market` (for disambiguation).
    * I don't know if eTrade is still very popular, considering they shut down most of their UK and EU operations few years ago and only US persons should nowadays have eTrade accounts (which is fiscally inoptimal vs Belgium scheme).

That being said, this is more of a mid-term improvement because again: I love this project, this works very well and so long that it works with JustETF for most of the cases, it is not an emergency.

**Comment by samjmck** [comment]
The problem with using OpenFIGI is that it doesn't tell us whether the fund is accumulating or not which is required to be able to determine the tax rate. At this moment, I think JustETF is adequate. The main risk is them blocking our requests like Yahoo Finance, but this is a concern with any data provider to be honest. It's really a cat and mouse game. I just have to change to a different website if we get blocked again.
