### ISSUE TITLE
IBKR partial fills exported as separate trades -> TOB ceiling not taken into account

### ISSUE THREAD

**Issue by daviddem1971** [samjmck/tobcalc#11]
When I follow your instructions to export the csv file from IB, my trades that filled in several partial fills are considered as separate trades, and if that trade was large enough that the TOB cap should be met, this causes tobcalc to not take the cap into account.

See attached csv file for an example of such trade.

Also if I try to manually modify the csv to merge the partial fills into a single trade, tobcalc then refuses to import it? Any mod I do to the csv seems to cause tobcalc to refuse to import it.

Could you maybe provide an option to the user to merge several trades into one (same as you provide an option to untick some trades when importing).

[tobcalc.csv](https://github.com/samjmck/tobcalc/files/12593815/tobcalc.csv)

**Comment by samjmck** [comment]
Thanks for raising this issue.

A few things:
1. tobcalc does currently not support the ceiling. Will look into implementing this in the coming days and update this issue.
2. tobcalc is sensitive to the format of the spreadsheet files (xlsx, csv etc). For csv files, you should edit them through a text editor instead of through spreadsheet software like Apple Numbers or Excel to keep the formatting. Did you use a text editor?
3. I agree that merge functionality would be useful. Will also look into making this.

**Comment by samjmck** [comment]
Solved in #22
