### ISSUE TITLE
How to test with local sources or tobcalc-lib ?

### ISSUE THREAD

**Issue by samsttx** [samjmck/tobcalc#29]
Hi,

I made a modification on the tobcalc-lib project and I would like to try it on tobcalc UI.
Since the lib is made with Deno there is no package.json and I don't know to link to my local sources

Does anyone have any advice for me ?

Thanks

**Comment by samjmck** [comment]
Good point. I will be looking into this today and will let you know if I find a solution.

**Comment by samjmck** [comment]
I have added a script to tobcalc-lib that allows you to build the package for npm locally, with a guide on how to use it here: https://github.com/samjmck/tobcalc-lib/blob/master/docs/frontend_testing.md

If you use the [`test-with-lib`](https://github.com/samjmck/tobcalc/tree/test-with-lib) branch for the frontend with that new lib script, you should be able to test it. I haven't merged it with master because I can't get `npm run build` to work, but `npm run dev` does work. Let me know how it goes.

**Comment by samsttx** [comment]
Excellent, looks like its working. I can work with that. 
Thanks.
