### ISSUE TITLE
idea/suggestion: use the IBKR API to fetch the CSV

### ISSUE THREAD

**Issue by sdiepend** [samjmck/tobcalc#3]
I was writing my own project in Python to file my TOB and found out that IBKR allows to fetch the csv generated by a flex query using the "API".

IBKR documentation: https://guides.interactivebrokers.com/am/am/reports/flex_web_service_version_3.htm

example code in Python:

```
FLEX_WEB_SERVICE_TOKEN = ''
QUERY_ID = ''

response = requests.get(f'https://gdcdyn.interactivebrokers.com/Universal/servlet/FlexStatementService.SendRequest?t={FLEX_WEB_SERVICE_TOKEN}&q={QUERY_ID}&v=3')

root = ET.fromstring(response.text)
reference_code = root[1].text

flex_response = requests.get(f'https://gdcdyn.interactivebrokers.com/Universal/servlet/FlexStatementService.GetStatement?q={reference_code}&t={FLEX_WEB_SERVICE_TOKEN}&v=3')

csvStringIO = StringIO(flex_response.text)
df = pd.read_csv(csvStringIO, sep=",")
```

**Comment by samjmck** [comment]
Interesting, I wasn't aware of this API. However, using this in tobcalc would require sending your personal token to the tobcalc servers which would be a security risk. The transaction history csvs/spreadsheets are processed on the client-side for the same reason: we want to minimise the amount of data that is sent to the server so that if the servers were ever breached, that there wouldn't be any sensitive user information to leak. I also think it's easier for less technical users to export a csv than generating a token.

What I could do is make the core library available as a standalone Deno module. Then you could import library and use the IBKR adapter with the flex service. The adapter accepts any `Blob` of data, regardless of where it comes from. An example could be 

```ts

// Environment variables FLEX_WEB_SERVICE_TOKEN and possibly other variables that are needed
const url = `https://interactivebrokers.com/get_statement?token=${Deno.env.get("FLEX_WEB_SERVICE_TOKEN")}`;
const flexServiceResponse = await fetch(url);

const brokerTransactions = await IBKRAdapter(await flexServiceResponse.blob());
const taxableTransactions = await getTaxableTransactions(brokerTransactions);
let i = 0;
for(const taxableTransaction of taxableTransactions) {
   const taxRate = getTaxRate(taxableTransaction);
   const taxValue = taxRate * taxableTransaction.value;
   console.log(`Transaction #${++i}: ${formatMoney(taxableTransaction.value)}, tax rate ${taxRate * 100}%, tax ${formatMoney(taxValue)}`);
}
```

And then you could use your own program if it's less work for you than using tobcalc.

**Comment by sdiepend** [comment]
I appreciate you're carefulness and taking the security risks into consideration! Although I think over time usability wins over  these potential risks, you could also provide the different options and state the involved risks? 

My program/tool does less, next up is generating the PDF :) But my endgoal was/is to provide it to other users as well together with other financial tools.

Anyway, just wanted to let you know this exists.

**Comment by samjmck** [comment]
A compromise might be keeping the token in the browser so that the server doesn't have to store it anywhere and that the user sends the token every time they want to fetch their transaction history. The problem then would be that there's no way to guarantee the user that we aren't actually storing the token anywhere and are also not using it. I'm also don't know enough about storage and crypto APIs/standards in browsers to be able to implement this properly. But maybe this is something to look at in the future if e.g. someone would like to develop a fully local app in Electron or something else, then there is no server (and no proxies) needed.
