### ISSUE TITLE
VWCE name currently matches the fund name from FOD Financiën and 1,32% tax is applied

### ISSUE THREAD

**Issue by muscovitebob** [samjmck/tobcalc#4]
This contradicts the documentation. Either the docs should be modified or an exception added.

**Comment by samjmck** [comment]
I suspect this is because I recently updated tobcalc to use Yahoo Finance for security data (including fund names) instead of Investing.com. The documentation should be updated in that case.

In the future, I would like to add some kind of "security store" interface to the codebase so that custom sources can be used for securities data, e.g. Yahoo Finance, Google Finance or even a manually created source. This way, the user could choose the fund's name and change it so it doesn't (or does) match the information in the FSMA's list if they believe the default behaviour is incorrect.

**Comment by adragan10** [comment]
For me VWCE has the same name as in Trading212 but the rate should be 0.12 instead of 1.32

**Comment by samjmck** [comment]
The [dev](https://github.com/samjmck/tobcalc/tree/dev) branch's interface allows you to override tax rates by ISIN now which addresses this issue. You can see it live at [dev.tobcalc.com](https://dev.tobcalc.com). [The documentation has also been updated](https://github.com/samjmck/tobcalc/blob/dev/docs/problem-with-registered-funds.md) in that branch to reflect the fact that the Yahoo Finance name, which tobcalc uses, matches the name used by the FSMA, so VWCE is recognised as registered.

To set the rate to 0.12%, add VWCE's ISIN (`IE00BK5BQT80`) to the override table with the rate 0.12%. 

I hope to merge the dev branch with master soon.
