### ISSUE TITLE
ETF IE00BDBRDM35 considered as a stock (0.35% TOB)

### ISSUE THREAD

**Issue by vivienbo** [samjmck/tobcalc#5]
Some `ETF` are treated as `stock` by TOBcalc which applies a 0.35% tax rate.

**Example**
ISIN Code | ETF Name (and link to PRIIPS)
-|-
IE00BDBRDM35 | [iShares Global Aggregate Bond UCITS ETF - Hedged EUR Accu](https://www.blackrock.com/fr/intermediaries/literature/kiid/eu-priips-ishares-core-global-aggregate-bond-ucits-etf-eur-hedged-acc-ie00bdbrdm35-en.pdf)

The PRIIPS KID states it is a `fund`, managed by `iShares III PLC` which from my understanding is a SICAV/BEVEK.

Note:
* I am aware I can customize the tax rate on the interface as a workaround
* However I think it is worth investigate why this classification happen (dataset issue? or other...)

**Comment by samjmck** [comment]
This is indeed an issue with the dataset. tobcalc searches the ISIN on Yahoo Finance and uses the search results to determine the type of security which could be stock, ETF or something else. 

From my understanding, the mapping of the `quoteType` field in the Yahoo Finance search results is as followed:
- `EQUITY` generally means stock
- `ETF` means ETF
- `MUTUALFUND` means mutual fund

Here's the exact code that handles this: 

https://github.com/samjmck/tobcalc/blob/master/src/data.ts#L155-L175

I believe the problem here is that the quote type of this security is `EQUITY` while it should be `ETF`. 

Looking at `IE00B4L60045`, another bond ETF, we can see that this is correctly identified as an ETF on Yahoo Finance:

<img width="507" alt="Screenshot 2023-03-20 at 09 34 36" src="https://user-images.githubusercontent.com/25828757/226286829-41c93d23-4efd-4292-9148-ba2aeb1deb9c.png">

**Possible solutions**

I could maybe add some code to check if the title of the security in Yahoo Finance contains the word "ETF", but that obviously is quite hacky and again, isn't a deterministic way to determine the type of security of a current ISIN.

As you already mentioned, it's also possible to override this in the interface of tobcalc. 

If this is a popular ETF within the BEFIRE community, I can look into manually overriding the security type within the code i.e. hardcoding the details.

**Comment by vivienbo** [comment]
Hello,

I don't know how popular it is in the BEFire community however for sure, this one is part of the [r/BEFire Beginner's guide to index investing in Belgium](https://www.reddit.com/r/BEFire/comments/fcbay6/getting_started_a_beginners_guide_to_investing_in/) section 3 `Bonds`.

So it's more likely people who started last 36 months are to buy at least this one to complement their portfolio.

For the other bonds ETF I own, indeed there is no issue faced.

**Comment by samjmck** [comment]
Fixed in 1e743e1

https://github.com/samjmck/tobcalc/blob/1e743e1504494c3cbc7c8ca8d1a32be4912cc0a1/site/src/overrides.ts#L20-L58

May take some time for your browser cache to update with the newest version.
